# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.

project_id = "xero-integration"

[api]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false

[db.migrations]
enabled = false

[db.seed]
enabled = false

[db.network_restrictions]
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = false

[storage]
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = true
port = 54327
backend = "postgres"
